Source/Api/Exceptionless.Api.csproj
Source/Api/packages.config
Source/Core/Exceptionless.Core.csproj
Source/Core/Extensions/StorageExtensions.cs
Source/Core/Jobs/EventPostsJob.cs
Source/Core/Pipeline/EventPipeline.cs
Source/Core/Repositories/Exceptions/DocumentNotFoundException.cs
Source/Core/packages.config
Source/Insulation/Exceptionless.Insulation.csproj
Source/Insulation/packages.config
Source/Jobs/DailySummary/DailySummaryJob.csproj
Source/Jobs/DailySummary/packages.config
Source/Jobs/DownloadGeoIPDatabase/DownloadGeoIPDatabaseJob.csproj
Source/Jobs/DownloadGeoIPDatabase/packages.config
Source/Jobs/EventNotification/EventNotificationsJob.csproj
Source/Jobs/EventNotification/packages.config
Source/Jobs/EventPost/EventPostsJob.csproj
Source/Jobs/EventPost/packages.config
Source/Jobs/EventUserDescription/EventUserDescriptionsJob.csproj
Source/Jobs/EventUserDescription/packages.config
Source/Jobs/MailMessage/MailMessageJob.csproj
Source/Jobs/MailMessage/packages.config
Source/Jobs/RetentionLimit/RetentionLimitsJob.csproj
Source/Jobs/RetentionLimit/packages.config
Source/Jobs/WebHook/WebHooksJob.csproj
Source/Jobs/WebHook/packages.config
Source/Jobs/WorkItem/WorkItemJob.csproj
Source/Jobs/WorkItem/packages.config
Source/Tests/Exceptionless.Api.Tests.csproj
Source/Tests/packages.config

* There is an issue where loading files that no longer exist was
throwing exceptions.
* Fixed an issue where posts where projects no longer existed was
throwing a null reference exception or was not being completed properly.
* Fixed an issue where event post data wasn't being deleted if the
archived file already existed.

Fixed a few issues where event posts job wasn't processing some queue items

---

Source/Api/Controllers/UserController.cs

Fix verifying email address with an existing token fails

---

Source/Core/Exceptionless.Core.csproj
Source/Core/Models/Event.cs
Source/Core/Plugins/EventProcessor/Default/03_ManualStackingPlugin.cs
Source/Core/Plugins/EventProcessor/Default/20_ErrorPlugin.cs
Source/Core/Plugins/EventProcessor/Default/30_SimpleErrorPlugin.cs
Source/Tests/Exceptionless.Api.Tests.csproj
Source/Tests/Plugins/ManualStackingTests.cs

Added manual stacking plugin. Don't add signature data in the error plugin if already added manual stacking. Error plugin still sets message and target info.

Manual stacking

---

Source/Core/Exceptionless.Core.csproj
Source/Core/Extensions/EventExtensions.cs
Source/Core/Extensions/JsonExtensions.cs
Source/Core/Models/Data/ManualStackingInfo.cs
Source/Core/Models/Data/StackingInfo.cs
Source/Core/Models/Event.cs
Source/Core/Pipeline/010_AssignToStackAction.cs
Source/Core/Plugins/EventProcessor/Default/03_ManualStackingPlugin.cs
Source/Core/Plugins/EventProcessor/Default/20_ErrorPlugin.cs
Source/Core/Plugins/Formatting/Default/05_ManualStackingFormattingPlugin.cs
Source/Tests/Plugins/ManualStackingTests.cs

https://github.com/exceptionless/Exceptionless.Net/pull/82

Updated manual stacking implementation

---

Source/Core/Plugins/Formatting/Default/10_SimpleErrorFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/20_ErrorFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/30_NotFoundFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/40_UsageFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/50_SessionFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/60_LogFormattingPlugin.cs
Source/Core/Plugins/Formatting/Default/99_DefaultFormattingPlugin.cs
Source/Core/Serialization/EmptyCollectionElasticContractResolver.cs
Source/Core/Serialization/ExceptionlessContractResolver.cs
Source/Core/Serialization/LowerCaseUnderscorePropertyNamesContractResolver.cs

https://github.com/exceptionless/Exceptionless.Net/issues/63

Don't serialize any dictionary keys

---

CONTRIBUTING.md

Replaced gitter link with link to the Slack channel

Removed gitter link

---

src/Exceptionless.Api/Controllers/AdminController.cs
src/Exceptionless.Api/Controllers/EventController.cs
src/Exceptionless.Api/Controllers/OrganizationController.cs
src/Exceptionless.Api/Controllers/ProjectController.cs
src/Exceptionless.Api/Controllers/TokenController.cs
src/Exceptionless.Api/Controllers/UserController.cs
src/Exceptionless.Api/Extensions/HttpExtensions.cs
src/Exceptionless.Api/Security/AuthMessageHandler.cs
src/Exceptionless.Core/Extensions/PersistentEventExtensions.cs
src/Exceptionless.Core/Extensions/StringExtensions.cs
src/Exceptionless.Core/Filter/FieldAggregationProcessor.cs
src/Exceptionless.Core/Filter/QueryProcessorVisitor.cs
src/Exceptionless.Core/Plugins/Formatting/Default/30_NotFoundFormattingPlugin.cs
src/Exceptionless.Core/Plugins/Formatting/Default/60_LogFormattingPlugin.cs
src/Exceptionless.Core/Plugins/Formatting/Default/99_DefaultFormattingPlugin.cs
tests/Exceptionless.Api.Tests/Authentication/TestDomainLoginProvider.cs
tests/Exceptionless.Api.Tests/Search/EventIndexTests.cs
tests/Exceptionless.Api.Tests/Search/StackIndexTests.cs
tests/Exceptionless.Api.Tests/Utility/EventData.cs

#228 
ToLower methods changed with ToLowerInvariant method.

Turkish culture problem solved.

---

src/Exceptionless.Core/Extensions/QueueExtensions.cs
src/Exceptionless.Core/Models/Queues/EventPostInfo.cs
src/Exceptionless.Core/Settings.cs
tests/Exceptionless.Api.Tests/Jobs/EventPostJobTests.cs
tests/Exceptionless.Api.Tests/app.config

Added setting for archive enabled

---

Exceptionless.sln
Exceptionless.sln.DotSettings
src/Exceptionless.Core/Bootstrapper.cs
src/Exceptionless.Core/Jobs/StackEventCountJob.cs
src/Exceptionless.Core/Pipeline/060_UpdateStatsAction.cs
src/Exceptionless.Core/Repositories/Interfaces/IStackRepository.cs
src/Exceptionless.Core/Repositories/StackRepository.cs
src/Exceptionless.Core/Services/StackService.cs
src/Jobs/StackEventCountJob/Program.cs
src/Jobs/StackEventCountJob/Properties/launchSettings.json
src/Jobs/StackEventCountJob/StackEventCountJob.csproj
tests/Exceptionless.Api.Tests/Services/StackServiceTests.cs
tests/Exceptionless.Api.Tests/Stats/AggregationTests.cs

Fix the issue https://github.com/exceptionless/Exceptionless/issues/328, and the pr can reduce the notification messages of the issue https://github.com/exceptionless/Exceptionless/pull/342

Increment stack event count with separate job and run every 5 seconds instead of every event processed.

---

src/Exceptionless.Core/Jobs/DailySummaryJob.cs

These two somehow returned null here.

Fix NRE in DailySummaryJob

---

src/Exceptionless.Core/Models/Token.cs
src/Exceptionless.Core/Repositories/Configuration/Indexes/OrganizationIndex/TokenIndexType.cs
src/Exceptionless.Core/Utility/SampleDataService.cs
src/Exceptionless.Core/Validation/TokenValidator.cs
src/Exceptionless.Web/Models/Token/UpdateToken.cs
src/Exceptionless.Web/Models/Token/ViewToken.cs
src/Exceptionless.Web/Security/ApiKeyAuthenticationHandler.cs
tests/Exceptionless.Tests/Controllers/EventControllerTests.cs
tests/Exceptionless.Tests/Controllers/TokenControllerTests.cs
tests/Exceptionless.Tests/Extensions/RequestExtensions.cs
tests/Exceptionless.Tests/Validation/TokenValidatorTests.cs

Don't merge this until we've had more testing and discussion. Fixes #355

#355 - Ability to disable an api key.

---

src/Exceptionless.Web/Startup.cs

Allow forwarded IP addresses behind reverse proxy

---

src/Exceptionless.Job/JobRunnerOptions.cs
src/Exceptionless.Job/Program.cs

Job: Use nameof()

---

src/Exceptionless.Web/ClientApp/grunt/task-configs/connect.js

Fixes #1304 wrapping cert path to allow blank space in path

---

src/Exceptionless.Web/ClientApp/app/event/event-controller.js

Fixes #1360: Additional Exception.Data items are not shown in the ui.

---

src/Exceptionless.Job/JobRunnerOptions.cs
src/Exceptionless.Job/Program.cs

Change jobs to run on cron schedule

---

README.md

Briefly describe the nature of the change, including the issue being addressed
and the motivation behind it. If applicable, mention any dependencies required
for this change.

Update README.md for node 20

---

src/Exceptionless.Core/Billing/StripeEventHandler.cs
src/Exceptionless.Core/Extensions/UserExtensions.cs
src/Exceptionless.Core/Jobs/DailySummaryJob.cs
src/Exceptionless.Core/Jobs/EventNotificationsJob.cs
src/Exceptionless.Core/Jobs/EventPostsJob.cs
src/Exceptionless.Core/Jobs/WorkItemHandlers/UserMaintenanceWorkItemHandler.cs
src/Exceptionless.Core/Models/WorkItems/UserMaintenanceWorkItem.cs
src/Exceptionless.Core/Repositories/UserRepository.cs
src/Exceptionless.Core/Services/OrganizationService.cs
src/Exceptionless.Core/Utility/SampleDataService.cs
src/Exceptionless.Web/Controllers/AdminController.cs
src/Exceptionless.Web/Controllers/AuthController.cs
src/Exceptionless.Web/Controllers/UserController.cs
tests/Exceptionless.Tests/Controllers/AuthControllerTests.cs
tests/Exceptionless.Tests/Jobs/CloseInactiveSessionsJobTests.cs
tests/Exceptionless.Tests/Jobs/EventPostJobTests.cs
tests/Exceptionless.Tests/Mail/MailerTests.cs
tests/Exceptionless.Tests/Pipeline/EventPipelineTests.cs

- Ensure all users are saved with immediate consistency.

Ensure Email Verification status goes through one code path, added maintenance item to reset and resend emails.

---

.github/workflows/build.yaml

https://github.com/marocchino/sticky-pull-request-comment?tab=readme-ov-file#error-resource-not-accessible-by-integration

Added write permission for pr test coverage

---

src/Exceptionless.Core/Repositories/ProjectRepository.cs
src/Exceptionless.Core/Repositories/StackRepository.cs
src/Exceptionless.Core/Repositories/WebHookRepository.cs
src/Exceptionless.Web/Controllers/ProjectController.cs
src/Exceptionless.Web/Controllers/WebHookController.cs

See commits for more detailes.

Fixed some repository caching bugs and improved code gen

---

src/Exceptionless.Web/ClientApp/src/lib/features/events/components/filters/organization-defaults-faceted-filter-builder.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-actions.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-boolean.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-builder.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-drop-down.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-keyword.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-multi-select.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-number.svelte
src/Exceptionless.Web/ClientApp/src/lib/features/shared/components/faceted-filter/faceted-filter-string.svelte
src/Exceptionless.Web/ClientApp/src/routes/(app)/+page.svelte
src/Exceptionless.Web/ClientApp/src/routes/(app)/issues/+page.svelte
src/Exceptionless.Web/ClientApp/src/routes/(app)/stream/+page.svelte

- Accessability imporovements and way better keyboard navigation.
- Automatically show project filters
- Fixed boolean filters
- Added ability to quickly create keyword filters

Next: filtering improvements
