Source/Clients/Shared/Extensions/WebRequestExtensions.cs
Blake,
Here you go... seems to do the trick.  I didn't look into the Elevated Permissions bit..
Must close stream for AsyncWaitHandle for a HttpWebRequest (bombs in SL)
but good practice.
The HttpWebRequest for SL does not have a UserAgent property so must set
via headers.
=> Fixes for Silverlight

Libraries/Create-Release.ps1, Source/Api/Web.config, Source/Insulation/Exceptionless.Insulation.csproj, Source/Insulation/packages.config
http://www.hanselman.com/blog/BackToBasicsDynamicImageGenerationASPNETControllersRoutingIHttpHandlersAndRunAllManagedModulesForAllRequests.aspx
@ejsmith  I tried looking back in history and figuring out why this was added but
couldn't find anything other than it was added as a generic commit in 2012.  I did a really quick test and nothing seems broken.
=> Removed runAllManagedModulesForAllRequests setting for performance reasons

Source/Api/Controllers/AuthController.cs, Source/Core/Settings.cs, Source/Tests/Controllers/AuthControllerTests.cs, Source/Tests/Exceptionless.Api.Tests.csproj
Adds logic to SignupAsync to allow InviteTokens to override the EnableAccountCreation flag when the EnableInvitedUserCreation flag is set. Requested PR from issue #147.
Unit tests are modeled after existing controller tests but are flaky when run as a group because of xUnit's async task runner and the updating of the global Settings. Let me know if you want to trim this down to just the logic change.
=> Add setting to allow InviteToken to override EnableAccountCreation

Source/Api/Controllers/EventController.cs, Source/Api/Controllers/ProjectController.cs, Source/Core/Extensions/PersistentEventExtensions.cs, Source/Core/Jobs/CloseInactiveSessionsJob.cs, Source/Tests/Jobs/CloseInactiveSessionsJobTests.cs
This adds new api fire and forget end point for sending heartbeats.
@ejsmith do you think we should decrease the job time and inactive session period from 10 minutes to something smaller so things run more often?
=> Added new heartbeat api endpoint

Source/Api/Web.config
This should reduce the incidence of issue #239 and make it more consistent with how other connection string are handled in the application.
=> Added empty LdapConnectionString to web.config

Source/Api/Controllers/EventController.cs
Attributes `OverrideAuthorization` and `Authorize` were commented out, making the client unable to use this API (due Authorization failed.)
=> Fixed authorization on SetUserDescriptionAsync

src/Exceptionless.Core/Mail/SmtpMailSender.cs
Any receiver having auto-reply enabled will result in an auto-reply mail being sent back to the sender address for any notifications sent out from Exceptionless. I.e. for no-reply addresses will end up bouncing with several retries and mails received as a consequence.
By including certain headers to the mails sent will make the receiver (server) skip sending auto-reply for these types of mails.
Details of the related headers:
- http://www.redmine.org/issues/19558
- https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/
=> Suppress auto-reply

src/Exceptionless.Api/Web.config
If URL re-writing is not enabled, the base url in the app config must end with "/#!" or links in emails will not work. (verification email link ends up redirecting to the dashboard, and doesn't actually verify the email)
=> Default BaseURL is misleading

src/Exceptionless.Api/Utility/Results/OkWithHeadersContentResult.cs, src/Exceptionless.Core/Extensions/UriExtensions.cs
Preparement: We have posted many logs with the same Chinese tag "测试"
Scenario: In the search box enter keyword "测试", there will be many pages records. But when clicking the next page button, the page will be just refreshed and stay at the first page instead of navigating to next page records correctly.
Root cause: The previous page url and next page url will be generated incorrectly when search with Chinese characters.
While debugging source code, the baseUrl will be like
```
https://mywebsite/api/v2/stacks/frequent?filter=fixed:false+hidden:false+(测试)&limit=10&mode=summary&offset=480m
```
and the value of url.Query will be like
```
?filter=fixed:false+hidden:false+(%E6%B5%8B%E8%AF%95)&limit=10&mode=summary&offset=480m
```
So when replace the query to empty string, nothing will happen.
I …
=> Fix bug the previous page url and next page url will be generated incorrectly

src/Exceptionless.Core/Settings.cs, src/Exceptionless.Insulation/Bootstrapper.cs
Add `QueueScope` in settings used to generate queue name in redis or windows azure. For exceptionless servers in the load balance environment, avoid the absolutely separated data storage in elasticsearch when using `AppScope`, and avoid errors of chaos event reference among servers by using the default generated queue name without server specified prefix.
=> Add setting 'QueueScope' for server load balance environment. fix #326

src/Exceptionless.Api/Extensions/SwaggerExtensions.cs, src/Exceptionless.Api/Startup.cs
Cleans up the swagger doc around versioned api's. No longer have optional {version} params in swagger spec. No longer have v1 and v2 api's in the same swagger spec. (there are now two exported swagger specs)
=> Add proper swagger support for a versioned api

src/Exceptionless.Web/Startup.cs
Two changes are required.
1) .less files need to be served.
2) gravatar needs to be allowed for user images (CSP).
=> Enable running UI in Web

src/Exceptionless.Web/appsettings.Production.yml, src/Exceptionless.Web/appsettings.Staging.yml, src/Exceptionless.Web/appsettings.yml
On Windows 97% of `EventController.PostAsync` is console logging
Switching it to ansi mode (for Development) and no colors for Staging/Production reduces that to 75% https://github.com/serilog/serilog-sinks-console/issues/58
Changing it to be >= `Warning` for Staging/Production removes the cost entirely (assuming no errors 😉)
=> Reduce console logging costs

src/Exceptionless.Web/Controllers/AuthController.cs, src/Exceptionless.Web/Controllers/EventController.cs, src/Exceptionless.Web/Controllers/OrganizationController.cs, src/Exceptionless.Web/Controllers/ProjectController.cs, src/Exceptionless.Web/Controllers/UserController.cs, src/Exceptionless.Web/Controllers/WebHookController.cs, src/Exceptionless.Web/Extensions/LoggerExtensions.cs, src/Exceptionless.Web/Utility/Handlers/OverageMiddleware.cs
User `LoggerMessage.Define` to avoid allocations from boxing and params allocations from Information level logging; which occur regardless as to whether that level is enabled.
=> Web: Remove boxing and params allocations from Info logging calls

src/Exceptionless.Web/Utility/Handlers/ThrottlingMiddleware.cs
To indicate rate limiting; could also be `Status402PaymentRequired` to signal upgrade required?
When load testing `Status409Conflict` confused me as it suggested duplicate request issues.
=> Status409Conflict -> Status429TooManyRequests

src/Exceptionless.Core/Extensions/LoggerExtensions.cs, src/Exceptionless.Core/Jobs/CleanupDataJob.cs, src/Exceptionless.Core/Jobs/WebHooksJob.cs, src/Exceptionless.Web/Extensions/LoggerExtensions.cs
User `LoggerMessage.Define` to avoid allocations from boxing and params allocations from logging; which occur regardless as to whether that level is enabled.
=> Core: Remove boxing and params allocations from logging calls

src/Exceptionless.Core/Bootstrapper.cs, src/Exceptionless.Core/Pipeline/070_QueueNotificationAction.cs, src/Exceptionless.Core/Plugins/PluginManagerBase.cs, src/Exceptionless.Core/Plugins/WebHook/Default/000_LoadDefaultsPlugin.cs, src/Exceptionless.Core/Plugins/WebHook/Default/005_SlackPlugin.cs, src/Exceptionless.Core/Plugins/WebHook/Default/010_VersionOnePlugin.cs, src/Exceptionless.Core/Plugins/WebHook/Default/020_VersionTwoPlugin.cs, src/Exceptionless.Core/Plugins/WebHook/WebHookDataContext.cs, src/Exceptionless.Core/Plugins/WebHook/WebHookDataPluginManager.cs, src/Exceptionless.Web/Controllers/StackController.cs, tests/Exceptionless.Tests/Plugins/WebHookDataTests.cs, tests/Exceptionless.Tests/Utility/TestConstants.cs
- This allows you to send messages to discord using the slack url suffix,
- This doesn't work when promoting stacks.
I also had to base this off the usage branch due to metrics and some other minor changes
=> Added ability to send slack webhook messages if the url ends with /slack

src/Exceptionless.Core/Utility/SampleDataService.cs, src/Exceptionless.Web/Controllers/EventController.cs, src/Exceptionless.Web/Extensions/HttpExtensions.cs, src/Exceptionless.Web/Extensions/LoggerExtensions.cs, tests/Exceptionless.Tests/Controllers/EventControllerTests.cs, tests/Exceptionless.Tests/Controllers/ProjectControllerTests.cs
The project will never be set on the request by default.
=> Fixes #1228: Load project config from request and don't log out if project doesn't exist

src/Exceptionless.Web/ClientApp/app/event/event.tpl.html, src/Exceptionless.Web/ClientApp/app/event/extended-data-item-directive.js, src/Exceptionless.Web/ClientApp/app/event/extended-data-item-directive.tpl.html, src/Exceptionless.Web/ClientApp/app/event/tabs/promoted.tpl.html
Fixes https://github.com/exceptionless/Exceptionless/issues/1316
This change also effects anything that doesn't have a defined title:
=> Fixes #1316 Preserve extended data titles

src/Exceptionless.Web/ClientApp/app/event/event-controller.js, src/Exceptionless.Web/ClientApp/app/event/event.tpl.html
=> Fixes #1289 Promoting a tab named the same as default tabs causes it to be unselectable via UI

src/Exceptionless.Core/Pipeline/030_CheckForRegressionAction.cs, tests/Exceptionless.Tests/Pipeline/EventPipelineTests.cs
- There is an optimization to only check the regressed status on only stacks with a status of `Fixed`. As you can't regress from any other version.
- If an organization has premium features and the stack is marked fixed and doesn't regress then **those events will be discarded and won't count towards limits**.
The one downside to this implementation is that if you mark a stack as fixed, you will not see any users who are still experiencing the error to reach out to them, as those events will be discarded.
=> Discard fixed stack events that don't regress

src/Exceptionless.Web/ClientApp.angular/app/auth/signup-controller.js
The api already work this way.  You can sign up if EnableAccountCreation is true or if you have a valid token linked to an organization.  Currently the frontend wont submit when you enter with a token if EnableAccountCreation is false.
Here is the relevant api logic:
private async Task<bool> IsAccountCreationEnabledAsync(string? token)
{
if (_authOptions.EnableAccountCreation)
return true;`
if (String.IsNullOrEmpty(token))
return false;
var organization = await _organizationRepository.GetByInviteTokenAsync(token);
return organization is not null;
}
=> Account creation with token and AccountCreation false

.github/workflows/build.yaml, src/Exceptionless.Core/Configuration/MessageBusOptions.cs, src/Exceptionless.Core/Configuration/MetricOptions.cs, src/Exceptionless.Core/Configuration/QueueOptions.cs, src/Exceptionless.Core/Configuration/StorageOptions.cs
This allows you to use configuration like
```
MessageBus: provider=rabbitmq;
RabbitMQ: amqp://guest:guest@localhost:5672/vhost
```
=> Fixes #1526 - If provider connection string is specified use it.
